sql {
    driver = "rlm_sql_mysql"
    dialect = "mysql"

    # Dados do Container do Banco de Dados
    server = "db"
    port = 3306
    login = "wifi"
    password = "wifi"
    radius_db = "wifi"

    read_clients = no
    
    # Pool de conexões
    pool {
        start = 5
        min = 4
        max = 10
        spare = 3
    }
}